apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
  labels:
    app: capstone-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - name: capstone-app-container
        image: laxg66/capstone02:v1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app-service
spec:
  type: NodePort
  selector:
    app: capstone-app
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8082
    nodePort: 30082  # NodePort value; it will expose the service on this port
